/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>

/**
 * Configuracion de la flash
 */
void flash_cofig(void);

/**
 * Selecciona el HSE como sysclk
 */
void HSE_Config(void);
/**
 * Configurar el PLL  a 168MZh
 */
void PLL_Config(void);

int main(void)
{
	flash_cofig();
	HSE_Config();
	PLL_Config();
	printf("SYSCLK->%u\n",(int)SystemCoreClock);
    /* Loop forever */
	for(;;);
}

void flash_cofig(void){
	FLASH->ACR |= 1<<9;							//1: Instruction cache is enabled
	FLASH->ACR |= 1<<10;						//1: Data cache is enabled
	FLASH->ACR |= 1<<8;							//1: Prefetch is enabled
	//SE HABILITAN ALGUNOS CLOCK
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	RCC->APB1ENR |= RCC_APB1ENR_PWREN;
}

void HSE_Config(void){
	RCC->CR |= RCC_CR_HSEON;					//se habilita el HSE
	while(!(RCC->CR & RCC_CR_HSERDY));			//se espera que el HSE este listo
	RCC->CFGR = RCC_CFGR_SW_HSE;				//Se selecciona el HSE Como fuente sysclk
	while(!(RCC->CFGR & RCC_CFGR_SWS_HSE));		//se espera que se haga el cambio
	SystemCoreClockUpdate();
}

/**
 * @brief PLL config
 * configura el PLL  a 84MHz
 */
void PLL_Config(void){
	//HSE ENABLE
	HSE_Config();
	//PLL OFF
	RCC->CR &=~ RCC_CR_PLLON;
	while(RCC->CR & RCC_CR_PLLRDY);
	/*Configuracion de parametros del PLL*/
	RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;	//HSE fuente para el PLL
	/*Configuracion de M,N,P,Q*/
	/**
	 * Fsysclk = (Pll_clock_src * (N /M))/P
	 * M = 6
	 * N = 336
	 * P = 2
	 * Fsysclk = (8MHz*(336/8))/2 = 168MHz
	 */
	RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLM;
	RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLN;
	RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLP;


	RCC->PLLCFGR |= 8U;	//M = 8
	RCC->PLLCFGR |= 336U<<RCC_PLLCFGR_PLLN_Pos;	//N = 336
	RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLP;			//P = 2
	/*Habilitar el pll*/
	RCC->CR |= RCC_CR_PLLON;
	while(!(RCC->CR & RCC_CR_PLLRDY));
	/*Configurar los prescalers*/
	RCC->CFGR |= 0b101<<RCC_CFGR_PPRE1_Pos;		//APB1  0b101: AHB clock divided by 4
	RCC->CFGR |= 0b100<<RCC_CFGR_PPRE2_Pos;     //APB2  0b100: AHB clock divided by 2
	/*configure flash latency*/
	FLASH->ACR &=~ FLASH_ACR_LATENCY;
	FLASH->ACR |= FLASH_ACR_LATENCY_5WS;		//5 WS (6 CPU cycles) 150 < HCLK ≤168
	/*Configurar el pll como fuente de reloj de sistema*/
	RCC->CFGR &=~ RCC_CFGR_SW;
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while(!(RCC->CFGR & RCC_CFGR_SWS_PLL));		//wait PLL ready as system clock
	SystemCoreClockUpdate();
	return;
}
/******************************************************************************/
int __io_putchar(int ch){
	uint8_t c = ch & 0xFF;
	ITM_SendChar(c);
	return ch;
}
