/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
#include <stdio.h>


#define DUTY(x)			(uint16_t)((((float)x/100)*(TIM2->ARR + 1)) - 1)

/**
 * @brief generacion de PWM
 */
void TIMER2_CH1_Pwm(void);
/**
 * @brief timer para la medicion de frecuencia
 */
void TIMER3_CH1_IC_Config(void);


int main(void)
{
	TIMER2_CH1_Pwm();
	printf("CONFIGURACION STM32F103C8 CORRECTO\r\n");
	TIM2->CCR1 = DUTY(60);
	printf("DUTY->%d\r\n",60);
    /* Loop forever */
	for(;;);
}

/**
 * @brief generacion de PWM
 */
void TIMER2_CH1_Pwm(void){
	/*CONFIGURACION DEL PIN*/
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	//PA0 -> TIM2_CH1
	GPIOA->CRL &=~ (GPIO_CRL_CNF0 | GPIO_CRL_MODE0);	//reset
	GPIOA->CRL |= GPIO_CRL_CNF0_1 | GPIO_CRL_MODE0;		//alternative output push pull
														//maximum output speed 50MHz
	//configuracion del timer
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	/**
	 * Fpwm = Ftim/(ARR + 1)(PSC + 1)
	 * ARR = Ftim /(PSC +1)Fpwm - 1
	 * ARR = 72MHZ/(0 + 1)2000 - 1
	 * ARR = 36000 - 1
	 */
	TIM2->PSC = 0;
	TIM2->ARR = 36000 - 1;
	TIM2->CR1 = 0;
	/*configuracion del canal*/
	TIM2->CCMR1 &=~ (TIM_CCMR1_CC1S);				//CANAL COMO SALIDA
	TIM2->CCMR1 &=~ (TIM_CCMR1_OC1M);
	TIM2->CCMR1 |= 0x6U<<4;							//PWM MOD0 1
	TIM2->CCER &=~ (TIM_CCER_CC1P);					//sin polaridad
	TIM2->CCER |= TIM_CCER_CC1E;					//se habilita la salida
	/*habilitamos el conteo del timer*/
	TIM2->CR1 |= TIM_CR1_CEN;
	return;
}
/**
 * @brief timer para la medicion de frecuencia
 */
void TIMER3_CH1_IC_Config(void){

	return;
}

int __io_putchar(int ch){

	ITM_SendChar((uint32_t)ch);
	return ch;
}

