/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

//#define AHB1_BASE 	0x40020000UL
//#define RCC_BASE	(AHB1_BASE + 0x3800U)
//#define RCC_CR		*((volatile uint32_t *)(RCC_BASE + 0x00U))
/**
 * Configuracion de la flash
 */
void flash_cofig(void);
/**
 * Selecciona el HSE como sysclk
 */
void HSE_Config(void);
/**
 * Configurar el PLL  a 84MZh
 */
void PLL_Config(void);

uint32_t systemFreq;

int main(void)
{
	/*flash init*/
	flash_cofig();
	systemFreq = SystemCoreClock;
	/*HSE init*/
	HSE_Config();
	systemFreq = SystemCoreClock;
	/*PLL init*/
	PLL_Config();
	systemFreq = SystemCoreClock;
//	RCC_CR |= 1U<<18 | 1U<<16;
//	while(!(RCC_CR & 1U<<17));		//espera que el HSERDY
    /* Loop forever */
	for(;;);
}

void flash_cofig(void){
	FLASH->ACR |= 1<<9;							//1: Instruction cache is enabled
	FLASH->ACR |= 1<<10;						//1: Data cache is enabled
	FLASH->ACR |= 1<<8;							//1: Prefetch is enabled
	//SE HABILITAN ALGUNOS CLOCK
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	RCC->APB1ENR |= RCC_APB1ENR_PWREN;
}

void HSE_Config(void){
	RCC->CR |= RCC_CR_HSEON | RCC_CR_HSEBYP;	//se habilita el HSE en modo BYPASS
	while(!(RCC->CR & RCC_CR_HSERDY));			//se espera que el HSE este listo
	RCC->CFGR = RCC_CFGR_SW_HSE;				//Se selecciona el HSE Como fuente sysclk
	while(!(RCC->CFGR & RCC_CFGR_SWS_HSE));		//se espera que se haga el cambio
	SystemCoreClockUpdate();
}


void PLL_Config(void){
	/*(opcional) configurar el HSE*/

	//1. cofigurar la fuente de reloj del PLL

	//2. cofigure division factor (M, N, P , Q)
	/**
	  * 	f(VCO clock) = f(PLL clock input) Ã— (PLLN / PLLM)	(192 and 432 MHz)
	  * 	f(PLL general clock output) = f(VCO clock) / PLLP  	<= 84MHz
	  */
	//M

	//N

	//P
	/*3.Habilitar el PLL*/

	/*4. Cofigurar los prescalers (APB2, APB1)*/

	/*5. configurar la latencia de la flash*/
	FLASH->ACR &=~ FLASH_ACR_LATENCY;
	FLASH->ACR |= FLASH_ACR_LATENCY_2WS;

	/*seleccionar la fuente del sysclk*/

	SystemCoreClockUpdate();

}
