/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
/* Private includes ----------------------------------------------------------*/
#include "RCC.h"
#include "Config.h"
#include "USART.h"
#include <stdio.h>
/* Private typedef -----------------------------------------------------------*/


/* Private define ------------------------------------------------------------*/


/* Private macro -------------------------------------------------------------*/
#define USE_SWV			0
/* Private variables ---------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/


/* Private user code ---------------------------------------------------------*/
uint8_t txBuffer[200];
uint32_t len;
uint8_t rxBuffer[100];
USART_Handle_t usart2_handle;
/* External variables --------------------------------------------------------*/


int main(void)
{
	/*USART2 INIT*/
	usart2_handle.pUSARTx = USART2;

	USART_Init(USART2, 115200);
	printf("Configuracion correcta del USART2\r\n");
	/*LED INIT*/
	len = sprintf((char*)txBuffer,"Usart_SendSata correcto\r\n");

	USART_SendData(USART2, txBuffer, len);

//	USART_ReceiveData(USART2, rxBuffer, 10);
//	len = sprintf((char*)txBuffer,"BYTES RECIBIDOS->%s\r\n",rxBuffer);
//	USART_SendData(USART2, txBuffer, len);

	/*HABILITAR LA INTERRUPCION*/
	USART_IRQInterruptConfig(USART2_IRQn, ENABLE);
	USART_IRQPriorityConfig(USART2_IRQn, 1);

	len = sprintf((char*)txBuffer,"Usart_SendSataIT correcto\r\n");

	USART_SendDataIT(&usart2_handle, txBuffer, len);

	USART_ReceiveDataIT(&usart2_handle, rxBuffer, 10);
    /* Loop forever */
	for(;;){



	}
}


/*interrupt callback*/
void USART_ApplicationEventCallback(USART_Handle_t *pUSARTHandle,uint8_t ApEv){
	/*transmision completa*/
	if(USART_EVENT_TX_CMPLT == ApEv){
		printf("ENVIO COMPLETO IT\r\n");
	}
	/*recepcion completa*/
	if(ApEv == USART_EVENT_RX_CMPLT){
		printf("Se recibio por IT->%s\r\n",rxBuffer);
	}
}
/******************************************************************************/
int __io_putchar(int ch){
#if (USE_SWV== 1)
	ITM_SendChar((uint32_t)ch);
#else
	uint8_t c = ch & 0xFF;
	while(!(USART2->SR & USART_SR_TXE));  //espera hasta que usart este listo para transmitir otro byte
	USART2->DR = c;
#endif
	return ch;
}
