/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
/* Private includes ----------------------------------------------------------*/
#include "RCC.h"
#include "Config.h"
#include "USART.h"
#include <stdio.h>
/* Private typedef -----------------------------------------------------------*/


/* Private define ------------------------------------------------------------*/


/* Private macro -------------------------------------------------------------*/
#define USE_SWV			0
/* Private variables ---------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/

static void USART2_ConfigIT(void){
	/*configura la interrupcion para la recepcion*/
	USART2->CR1 |= USART_CR1_RXNEIE;			//generar IT cada vez que hay un dato para leerse
	//NVIC
	NVIC_SetPriority(USART2_IRQn,2);			//prioridad 2
	NVIC_EnableIRQ(USART2_IRQn);				//habilita la IT para el USART2
	return;
}
/* Private user code ---------------------------------------------------------*/
uint8_t txBuffer[200];
uint32_t len;
uint8_t rxBuffer[100];

/* External variables --------------------------------------------------------*/


int main(void)
{
	/*USART2 INIT*/
	USART_Init(USART2, 115200);
	printf("Configuracion correcta del USART2\r\n");
	/*LED INIT*/
	len = sprintf((char*)txBuffer,"Usart_SendSata correcto\r\n");

	USART_SendData(USART2, txBuffer, len);

	USART_ReceiveData(USART2, rxBuffer, 10);
	len = sprintf((char*)txBuffer,"BYTES RECIBIDOS->%s\r\n",rxBuffer);
	USART_SendData(USART2, txBuffer, len);


	GPIO_CLOCK_ENABLE(A)
	GPIOX_MODER(MODE_OUT,LED);
	GPIOX_PUPDR(MODE_PU_NONE,LED);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,LED);
	/*BUTTON INIT*/
	RCC->AHB1ENR |= GPIOX_CLOCK(BUTTON);
	GPIOX_MODER(MODE_DIGITAL_INPUT,BUTTON);
	GPIOX_PUPDR(MODE_PU_NONE,BUTTON);
    /* Loop forever */
	for(;;){



	}
}
/******************************************************************************/
int __io_putchar(int ch){
#if (USE_SWV== 1)
	ITM_SendChar((uint32_t)ch);
#else
	uint8_t c = ch & 0xFF;
	while(!(USART2->SR & USART_SR_TXE));  //espera hasta que usart este listo para transmitir otro byte
	USART2->DR = c;
#endif
	return ch;
}
