/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

/********************FUNCTION PROTOTYPE***************************************/
/*
 * @brief software delay function
 */
void delay_ms(uint32_t delay);


int main(void)
{
	/* ENABLE CLOCK FOR GPIOA*/
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	/*PA5 -> OUTPUT*/
	GPIOA->MODER |= GPIO_MODER_MODE5_0;									//General purpose output mode
	GPIOA->OTYPER &=~ GPIO_OTYPER_OT5;   								//Output push-pull
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED5_1 | GPIO_OSPEEDR_OSPEED5_0;	//Very high speed
	GPIOA->PUPDR &=~ (GPIO_PUPDR_PUPD5_1 | GPIO_PUPDR_PUPD5_0);			//no pull down/up
    /* Loop forever */
	for(;;){
		GPIOA->ODR ^= GPIO_ODR_OD5;										//toggle led
		delay_ms(100);

	}
}

void delay_ms(uint32_t delay){
	int i;
	for(;delay>0;delay--){
		for(i = 0;i<3195/2;i++);
	}
}
