/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
/* Private includes ----------------------------------------------------------*/
#include "RCC.h"
#include "Config.h"
#include "USART.h"
#include "Delay.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Private typedef -----------------------------------------------------------*/


/* Private define ------------------------------------------------------------*/


/* Private macro -------------------------------------------------------------*/
#define USE_SWV			0


#define DUTY(x)			(uint16_t)((((float)x/100)*(TIM2->ARR + 1)) - 1)
/* Private variables ---------------------------------------------------------*/

USART_Handle_t handle_usart2;

uint8_t rxBuffer[20];
uint8_t byte;
uint8_t i;

uint8_t duty;
/* Private function prototypes -----------------------------------------------*/


/* Private user code ---------------------------------------------------------*/
/**
 * @brief configura el timer 2 canal 3 como comparacion de salida
 */
static void TIMER2_CH3_OC_Config(void);

/* External variables --------------------------------------------------------*/


int main(void)
{
//	PLL_Config();
	/*delay init*/
#if USE_DELAY_US == 1
	delay_Init(SystemCoreClock/1000000);
#else
	delay_Init(SystemCoreClock/1000);
#endif
	/*UART INIT*/
	USART_Init(USART2, 115200);
	handle_usart2.pUSARTx = USART2;
	USART_IRQInterruptConfig(USART2_IRQn, ENABLE);
	USART_ReceiveDataIT(&handle_usart2, &byte, 1);
	/*CONFIGURAR EL TIMER 2	 */
	TIMER2_CH3_OC_Config();
	TIM2->CCR3 = DUTY(20);
	/*LED INIT*/

    /* Loop forever */
	for(;;){


	}
}



/**
 * @brief configura el timer 2 canal 3 como comparacion de salida
 */
static void TIMER2_CH3_OC_Config(void){
	/*configurar el canal*/
	//PB10-> TIM2_CH3
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	GPIOB->MODER &=~(GPIO_MODER_MODE10);
	GPIOB->MODER |= GPIO_MODER_MODE10_1;		//FUNCION ALTERNATIVA
	GPIOB->OSPEEDR |= GPIO_OSPEEDR_OSPEED10;	//VERY HIGH SPEED
	GPIOB->PUPDR &=~ (GPIO_PUPDR_PUPD10);		//NO PULL UP/DOWN
	GPIOB->AFR[1] &=~ GPIO_AFRH_AFSEL10;		//CLEAR
	GPIOB->AFR[1] |= (1U)<<(10-8)*4;
	/*1. Configura el PSC, ARR para determinar la FREQ del PWM*/
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	/**
	 * Fpwm = Ftim/(ARR + 1)(PSC + 1)
	 * ARR = Ftim /(PSC +1)Fpwm - 1
	 * ARR = 16MHZ/(15 + 1)1000 - 1
	 * ARR = 1000 - 1
	 */
	TIM2->PSC = 16 - 1;
	TIM2->ARR = 1000 - 1;
	/*Configurar el timer*/
	TIM2->CR1 = 0;
	/*Configurar el registro CCMR2	*/
	TIM2->CCMR2 &=~(TIM_CCMR2_CC3S); 			//configura el canal como salida
	TIM2->CCMR2 &=~(TIM_CCMR2_OC3M);
	TIM2->CCMR2 |= 6U<<4;						//PMW MODO 1
	TIM2->CCER &=~ (TIM_CCER_CC3P);
	TIM2->CCER |= TIM_CCER_CC3E;				//HABILITAR LA SALIDA DE COMPARACION
	/*habilitar el conteo del timer*/
	TIM2->CCR3 = 0;
	TIM2->CR1 |= TIM_CR1_CEN;					//HABILITA EL CONTEO

}

/*****************************************************************************/
void USART_ApplicationEventCallback(USART_Handle_t *pUSARTHandle,uint8_t event)
{
	if(event == USART_EVENT_RX_CMPLT){
		if(byte != 'X'){
				rxBuffer[i] = byte;
				i++;
		}else{
			rxBuffer[i] = '\n';
			duty = atoi((char*)rxBuffer);		//string -> integer
			memset(rxBuffer,0,i);				//limpia el buffer
			i = 0;
			TIM2->CCR3 = DUTY(duty);
		}

		USART_ReceiveDataIT(&handle_usart2, &byte, 1);
	}

}
//void USART2_IRQHandler(void)
//{
//	if(USART2->SR & USART_SR_RXNE){
//		byte = USART2->DR;
//		if(byte == 'X'){
//			rxBuffer[i] = '\n';
//			duty = atoi((char*)rxBuffer);		//string -> integer
//			memset(rxBuffer,0,i);				//limpia el buffer
//			i = 0;
//			TIM2->CCR3 = DUTY(duty);
//
//		}else{
//			rxBuffer[i] = byte;
//			i++;
//		}
//	}
//
//}

/******************************************************************************/
int __io_putchar(int ch){
#if (USE_SWV== 1)
	ITM_SendChar((uint32_t)ch);
#else
	uint8_t c = ch & 0xFF;
	while(!(USART2->SR & USART_SR_TXE));  //espera hasta que usart este listo para transmitir otro byte
	USART2->DR = c;
#endif
	return ch;
}

