/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
/* Private includes ----------------------------------------------------------*/
#include "RCC.h"
#include "Config.h"
#include <stdio.h>
/* Private typedef -----------------------------------------------------------*/


/* Private define ------------------------------------------------------------*/
#define EXTI_FALLING_IT			1
#define EXTI_RISING_IT			2
#define EXTI_FR_IT				3

#define GPIO_PIN_13				13
/* Private macro -------------------------------------------------------------*/
#define USE_SWV			0
/* Private variables ---------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/
static void EXTI13_Config(uint8_t typeIT);

void GPIO_EXTI_Callback(uint8_t pin);
/* Private user code ---------------------------------------------------------*/
uint32_t count;

/* External variables --------------------------------------------------------*/


int main(void)
{

	/*LED INIT*/
	GPIO_CLOCK_ENABLE(A)
	GPIOX_MODER(MODE_OUT,LED);
	GPIOX_PUPDR(MODE_PU_NONE,LED);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,LED);
	/*EXTI CONFIG*/
	EXTI13_Config(EXTI_FALLING_IT);
    /* Loop forever */
	for(;;){



	}
}


static void EXTI13_Config(uint8_t typeIT){
	/*enable clock*/
	RCC->AHB1ENR |= GPIOX_CLOCK(BUTTON);
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	/*configurar el pin como entrada*/

	GPIOX_MODER(MODE_DIGITAL_INPUT,BUTTON);
	GPIOX_PUPDR(MODE_PU_NONE,BUTTON);
	/*configurar el borde que dispara la interrupcion*/
	if(typeIT == EXTI_FALLING_IT)
		EXTI->FTSR |= 1U<<13;
	else if(typeIT == EXTI_RISING_IT)
		EXTI->RTSR |= 1U<<13;
	else{
		EXTI->FTSR |= 1U<<13;
		EXTI->RTSR |= 1U<<13;
	}
	/*habilitar el interrupt mask bit*/
	EXTI->IMR |= 1U<<13;
	/*asignar el pin a la linea EXTI*/
	SYSCFG->EXTICR[3] &=~ 0xFU<<4;
	SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI13_PC;
	/*Configurar los registros de la NVIC*/
	NVIC_SetPriority(EXTI15_10_IRQn,1);			//PRIORIDAD 1
	NVIC_EnableIRQ(EXTI15_10_IRQn);				//HABILITA LA INTERRUPCION EXTERNA
	//clear pending bit
	EXTI->PR |= 1u<<13;
	NVIC_ClearPendingIRQ(EXTI15_10_IRQn);

}

void GPIO_EXTI_Callback(uint8_t pin){
	if(pin == GPIO_PIN_13){
		//codigo
		count++;
		GPIOA->ODR ^= 1U<<5;
		printf("EVENTO->%d\n",(int)count);
	}

	return;
}

/******************************************************************************/
int __io_putchar(int ch){
#if (USE_SWV== 1)
	ITM_SendChar((uint32_t)ch);
#endif
	return ch;
}
