/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
/* Private includes ----------------------------------------------------------*/
#include "RCC.h"
#include "Config.h"
#include "Delay.h"
#include "USART.h"
#include <stdio.h>
/* Private typedef -----------------------------------------------------------*/


/* Private define ------------------------------------------------------------*/
#define ADC_CH0			0
#define ADC_CH1			1
#define ADC_CH2			2
#define ADC_CH3			3
#define ADC_CH4			4
#define ADC_CH5			5
#define ADC_CH6			6
#define ADC_CH7			7
#define ADC_CH8			8
#define ADC_CH9			9
#define ADC_CH10		10
#define ADC_CH11		11
#define ADC_CH12		12
#define ADC_CH13		13
#define ADC_CH14		14
#define ADC_CH15		15
/* Private macro -------------------------------------------------------------*/
/**
 * USE_SWV = 1 : el printf se usa para el la depuracion
 * USE_SWV = 0 : el printf se usa para el USART2
 */
#define USE_SWV			0
/* Private variables ---------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/
/**
 * @brief configuracion del ADC1
 */
void ADC1_InitScanMode(void);
/**
 * @brief configuracion de canales
 */
void ADC1_ChanelConfiguration(void);
/**
 * @brief lectura de un canal analogico
 */
uint16_t ADC1_ChannelRead(uint8_t chx);

/**
 * @brief cofiguurar el timer2 para generar base de tiempo
 */
void TIM2_Config(uint32_t freq);
/* Private user code ---------------------------------------------------------*/

uint16_t data;

uint16_t adcData[6];
uint8_t i = 0;
uint8_t endConversion  = 0;

float volt;
/* External variables --------------------------------------------------------*/


int main(void)
{
	/*delay Init*/
#if USE_DELAY_US == 1
	delay_Init(SystemCoreClock/1000000);
#else
	delay_Init(SystemCoreClock/1000);
#endif
	/*USART2 init*/
	USART_Init(USART2, 115200);
	/*ADC1 Configuratarion*/
	ADC1_InitScanMode();
	ADC1_ChanelConfiguration();
	TIM2_Config(20);
	RCC->AHB1ENR |= GPIOX_CLOCK(LED);
	GPIOX_MODER(MODE_OUT,LED);

    /* Loop forever */
	for(;;){
		if(endConversion){
			endConversion = 0;
			GPIOA->ODR ^= 1U<<5;
			printf("ADC_CH0->%u\r\n",adcData[0]);
			printf("ADC_CH1->%u\r\n",adcData[1]);
			printf("ADC_CH4->%u\r\n",adcData[2]);
			printf("ADC_CH8->%u\r\n",adcData[3]);
			printf("ADC_CH11->%u\r\n",adcData[4]);
			printf("ADC_CH10->%u\r\n",adcData[5]);
		}

	}
}
/******************************************************************************/

/**
 * @brief configuracion del ADC1
 */
void ADC1_InitScanMode(void){
	/*habilitar el reloj*/
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
	/*configurar el ADC*/
	ADC1_COMMON->CCR &=~ADC_CCR_ADCPRE;		//PCLK2 / 2 = 8MHZ
	ADC1->CR1 = 0;
	ADC1->CR2 = 0;
	ADC1->CR1 |= ADC_CR1_SCAN;				//habilita el modo scan
	//ADC1->CR2 |= ADC_CR2_EOCS;
	/*secuencia y la cantidad de conversiones*/
	ADC1->SQR1 |= 5U<<ADC_SQR1_L_Pos;		//6 conversiones
	ADC1->SQR3 |= ADC_CH0;					//1ra conversion
	ADC1->SQR3 |= ADC_CH1<<ADC_SQR3_SQ2_Pos;//2da conversion
	ADC1->SQR3 |= ADC_CH4<<ADC_SQR3_SQ3_Pos;//3ra conversion
	ADC1->SQR3 |= ADC_CH8<<ADC_SQR3_SQ4_Pos;//4ta conversion
	ADC1->SQR3 |= ADC_CH11<<ADC_SQR3_SQ5_Pos;//5ta conversion
	ADC1->SQR3 |= ADC_CH10<<ADC_SQR3_SQ6_Pos;//6ta conversion
	/*configurar el triger externo*/
	ADC1->CR2 |= ADC_CR2_EXTEN_0;			//disparo externo con flanco ascendente
	ADC1->CR2 |= 0x6U<<ADC_CR2_EXTSEL_Pos;	//Timer2 TRIGO event (Update event)
	/*interrupciones*/
	ADC1->CR1 |= ADC_CR1_EOCIE;				//habilita la IT para el flag EOC
	NVIC_EnableIRQ(ADC_IRQn);				//se habilita la interrupcion para el ADC
	/*encender el ADC*/
	ADC1->CR2 |= ADC_CR2_ADON;
	return;
}
/**
 * @brief configuracion de canales
 */
void ADC1_ChanelConfiguration(void){
	/*PA0->CH0, PA1->CH1, PA4->CH4, PB0->CH8, PC1->CH11, PC0->CH10*/
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN;
	//PA0, PA1 y PA4
	GPIOA->MODER |= GPIO_MODER_MODER0 | GPIO_MODER_MODER1 | GPIO_MODER_MODER4;
	GPIOA->PUPDR &=~(GPIO_PUPDR_PUPD0 | GPIO_PUPDR_PUPD1 | GPIO_PUPDR_PUPD4);
	//PB0
	GPIOB->MODER |= GPIO_MODER_MODE0;
	GPIOB->PUPDR &=~(GPIO_PUPDR_PUPD0);
	//PC0, PC1
	GPIOC->MODER |= GPIO_MODER_MODE0 | GPIO_MODER_MODE1;
	GPIOC->PUPDR &=~(GPIO_PUPDR_PUPD0 | GPIO_PUPDR_PUPD1);
	/*SAMPLING TIME*/
	ADC1->SMPR2 |= ADC_SMPR2_SMP1_0;						//15 Cycles
	ADC1->SMPR1 |= ADC_SMPR1_SMP11_1 | ADC_SMPR1_SMP11_0;	//56 Cycles

	return;
}

/**
 * @brief cofiguurar el timer2 para generar base de tiempo
 */
void TIM2_Config(uint32_t freq){
	uint32_t arr;
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	/*Configura el PSC y ARR*/
	/**
	 * update event = Ftim/(PSC + 1)*(ARR + 1)
	 * PSC = 0;
	 * ARR = 16MHZ/(freq) - 1:
	 */
	arr = SystemCoreClock/freq - 1;

	TIM2->PSC = 0;
	TIM2->ARR = arr;
	TIM2->CR2 &=~ TIM_CR2_MMS;
	TIM2->CR2 |= TIM_CR2_MMS_1;		//updata event como salida TRGO
	TIM2->CR1 |= TIM_CR1_CEN;		//habilita el conteo
	return;
}

/******************************************************************************/
void ADC_CvsCpltCallback(void){
	if(i<6){
		adcData[i] = ADC1->DR;		//se lee el valor convertido
		i++;
	}
	else{
		i = 0;
		endConversion = 1;
	}

}


/******************************************************************************/
int __io_putchar(int ch){
#if (USE_SWV== 1)
	ITM_SendChar((uint32_t)ch);
#else
	uint8_t c = ch & 0xFF;
	while(!(USART2->SR & USART_SR_TXE));  //espera hasta que usart este listo para transmitir otro byte
	USART2->DR = c;
#endif
	return ch;
}
