/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
/* Private includes ----------------------------------------------------------*/
#include "RCC.h"
#include "Config.h"
#include "cmsis_os.h"
#include "FreeRTOS.h"
#include "task.h"
#include "USART.h"
#include <stdio.h>
#include "semphr.h"
/* Private typedef -----------------------------------------------------------*/


/* Private define ------------------------------------------------------------*/


/* Private macro -------------------------------------------------------------*/
#define USE_SWV			0
/* Private variables ---------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/

void Task_Led(void *params);
void Task_Button(void const *params);

/* Private user code ---------------------------------------------------------*/
TaskHandle_t  led_handle;			//FreeRTOS
osThreadId    button_handle;		//cmsis-os (FreeRTOS)
SemaphoreHandle_t semButton = NULL;
/* External variables --------------------------------------------------------*/
osThreadDef(Button,Task_Button,2,0,configMINIMAL_STACK_SIZE);

int main(void)
{
	BaseType_t status;
	//USART 2 INIT
	USART_Init(USART2, 115200);

/*****************************************************************************/
	//freeRTOS

	semButton = xSemaphoreCreateBinary();

	status = xTaskCreate(Task_Led, "LED", configMINIMAL_STACK_SIZE, NULL, 2, &led_handle);
	configASSERT(status == pdPASS);
/*****************************************************************************/
	//CMSIS OS
	button_handle = osThreadCreate(osThread(Button), NULL);
	if(button_handle == NULL){
		while(1);
	}
/*****************************************************************************/
	//osKernelStart();
	printf("INICIO DEL KERNEL\r\n");
	vTaskStartScheduler();
    /* Loop forever */
	for(;;){



	}
}
/******************************************************************************/

void Task_Led(void *params){
	//led init
	GPIO_CLOCK_ENABLE(A)
	GPIOX_MODER(MODE_OUT,LED);
	GPIOX_PUPDR(MODE_PU_NONE,LED);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,LED);

	while(1){
		if(xSemaphoreTake(semButton,pdMS_TO_TICKS(2000))){
			GPIOX_ODR(LED) = 1;	//se enciende el led
			printf("EL BOTTON SE PRESIONO\r\n");
		}
		else{
			GPIOX_ODR(LED) = 0;
			printf("BUTON NO SE PRESIONO\r\n");
		}
		vTaskDelay(pdMS_TO_TICKS(1));
	}
}
void Task_Button(void const *params){
	//button init
	RCC->AHB1ENR |= GPIOX_CLOCK(BUTTON);
	GPIOX_MODER(MODE_DIGITAL_INPUT,BUTTON);
	GPIOX_PUPDR(MODE_PU_NONE,BUTTON);


	while(1){

		//verificamos que se presione el button
		if(!(GPIOX_IDR(BUTTON))){
			osDelay(100);
			xSemaphoreGive(semButton);
		}

		osDelay(1);
	}
}



/******************************************************************************/
int __io_putchar(int ch){
#if (USE_SWV== 1)
	ITM_SendChar((uint32_t)ch);
#else
	uint8_t c = ch & 0xFF;
	while(!(USART2->SR & USART_SR_TXE));  //espera hasta que usart este listo para transmitir otro byte
	USART2->DR = c;
#endif
	return ch;
}
